### ISSUE TITLE
Build only when original repository changes

### ISSUE THREAD

**Issue by schklom** [PussTheCat-org/docker-libremdb-quay#1]
If the original repository does not change, building everyday is a waste of resources for the server and for the user who will download a new image every time.

You can do this by:
- caching the repository's latest commit id (e.g. https://github.com/unixfox/periodic-build-with-github-actions/blob/master/.github/workflows/docker-build-onlyoffice.yml)
- or by storing it in a file and comparing every time the GitHubAction runs (e.g. https://github.com/schklom/Mirror-workflows/blob/main/.github/workflows/Sync%2Bbuild%2Bpush%20Mango.yml)

**Comment by TheFrenchGhosty** [comment]
>building everyday is a waste of resources for the server and for the user who will download a new image every time.

I don't care, GitHub is the one paying for the build, and users that pull every new image shouldn't.

Won't fix.

**Comment by schklom** [comment]
About 10 lines of code and it's done.

All it takes is
```yaml
jobs:
  job1:
    steps:
      - name: Get latest commit hash
        id: get-latest-commit
        run: |
          echo "::set-output name=commit::$(git ls-remote https://github.com/jiriks74/Docker-DocumentServer-Arm64.git | head -n1 | awk '{print $1;}')"
        shell: bash

      - uses: actions/cache@v2
        id: cache
        with:
          path: onlyoffice
          key: ${{ runner.os }}-${{ steps.get-latest-commit.outputs.commit }}-${{ hashFiles('**/lockfiles') }}

      - name: Do something (if there is a new version)
        if: steps.cache.outputs.cache-hit != 'true'
        run: echo 123

      - name: Do something else (if there is a new version)
        if: steps.cache.outputs.cache-hit != 'true'
        run: echo 456
```
